### ISSUE TITLE
Find which interval that each element of the vector belongs in

### ISSUE THREAD

**Issue by benmarwick** [edzer/intervals#2]
Hi, I'm curious to know if this package can efficiently help me with this problem. For each element of a vector, and a dataframe of intervals, I want to find out what interval each element belongs in, and get the result as a list of intervals that is the same length as the list of elements.
```
# Find which interval that each element of the vector belongs in

library(tidyverse)
elements <- c(0.1, 0.2, 0.5, 0.9, 1.1, 1.9, 2.1)

intervals <- 
  frame_data(  ~phase, ~start, ~end,
               "a",     0,      0.5,
               "b",     1,      1.9,
               "c",     2,      2.5
  )
```
I want an output something like:

```
[[1]]
phase 
  "a" 

[[2]]
phase 
  "a" 

[[3]]
phase 
  "a" 

[[4]]
character(0)

[[5]]
phase 
  "b" 

[[6]]
phase 
  "b" 

[[7]]
phase 
  "c" 
```

Does this package have a simple method for this kind of problem?

thanks!

**Comment by sainathadapa** [comment]
i'm not the package author, but try this out:
``` r
library(tidyverse)
elements <- c(0.1, 0.2, 0.5, 0.9, 1.1, 1.9, 2.1)

intervalsDF <- 
  frame_data(  ~phase, ~start, ~end,
               "a",     0,      0.5,
               "b",     1,      1.9,
               "c",     2,      2.5
  )

library(intervals)
library(rlist)

interval_overlap(
  Intervals(intervalsDF %>% select(-phase) %>% as.matrix, closed = c(TRUE, TRUE)),
  Intervals(data_frame(start = elements, end = elements), closed = c(TRUE, TRUE))
) %>% 
  list.map(data_frame(interval_index = .i, element_index = .)) %>% 
  do.call(what = bind_rows)

# A tibble: 6 × 2
#  interval_index element_index
#           <int>         <int>
#1              1             1
#2              1             2
#3              1             3
#4              2             5
#5              2             6
#6              3             7
```

**Comment by benmarwick** [comment]
Thanks, that certainly appears to do the job. Seems a bit unwieldy though.

**Comment by sainathadapa** [comment]
This works for most use cases, unless you have large number of time series intervals. I don't have a demonstrable code right now, but I think you can also use `data.table::foverlaps` to get to the answer.

**Comment by benmarwick** [comment]
Thanks, yes, I see an example of that at the in one of the answers to the question I posted on [SO](http://stackoverflow.com/q/41132081/1036500)

**Comment by archenemies** [comment]
This was a helpful "issue" - I came here to wonder why the Intervals package doesn't have a function to test for membership of an element in the set described by an Intervals object. After all, when a datatype describes sets, what could be more fundamental than testing for membership? Apologies if it is there in the library and I just didn't look hard enough...

The `intrval` package has `%[]%` but it seems to only deal with single intervals.

It looks like I have to define a function like this:

    interval_contains = function(xs,is) {
      stopifnot(is.numeric(xs))
      o=interval_overlap(
        Intervals(cbind(xs,xs)),
        is
      )
      unlist(Map(length,o))
    }

But one could easily satisfy @benmarwick by returning

      unlist(Map(function(x) {if(length(x)>0) x[[1]] else 0}, o))

Or perhaps the latter would belong in a separate function, `interval_where`.

Anyway, I think this library would benefit from some more high-level interfaces, like the above.

Not to mention infix operators...

There are some good answers on that SO thread, by the way.
